services:
  - type: web
    name: byteme-ri-booking
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: ADMIN_SECRET
        sync: false
      - key: CALLMEBOT_PHONE
        sync: false
      - key: CALLMEBOT_KEY
        sync: false
      # DATABASE_URL will be set after linking the Postgres service
    healthCheckPath: /
